# Generated by Django 5.2.6 on 2025-09-04 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_alter_supplier_options_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
