# Generated by Django 5.2.6 on 2025-09-04 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_alter_outflow_options'),
        ('products', '0002_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outflow',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='products.product', verbose_name='Produto'),
        ),
    ]
