# Generated by Django 5.2.6 on 2025-09-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0002_alter_inflow_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entrada de Produto'},
        ),
    ]
